### ISSUE TITLE
指差し機能

### ISSUE THREAD

**Issue by yogurt0713** [dadaa/tpp-light#1]
スマホやタブレットで指差しする場合、フル画面でも通常の表示画面でも指差しができるようにしたいです

**Comment by dadaa** [comment]
もしかすると、video のフルスクリーン上に表示を重ねるのはできないのかもしれません。
ともすれば、フルスクリーンを制限するような解決策になっちゃうかも。

**Comment by yogurt0713** [comment]
なるほど．oFでもフルスクリーンだとマウスコントロール効かなくなりますし，そういうものですよね．ボタンがあるとつい押してしまいそうなので，フルスクリーンの切り替えボタンを非表示にすれば画面表示を大きくしておけば大丈夫そうです．

**Comment by yogurt0713** [comment]
スマホ画面で見えるフルスクリーンの切り替えボタンですが，非表示にする必要はありません．スマホの人は主に指示される側で，その人はフルスクリーンで屋外を中継する人なので，指示することはほぼありませんし，中継中の画像を見る必要があるのでその場合，参加者の映っている画面は不要なので，フルスクリーン状態で中継します．自分が何か指さしが必要になった場合もしくは参加者の確認などする場合は，フルスクリーンから通常画面に戻ればよいので現状のインタフェースで問題ないことに気づきました
