### ISSUE TITLE
Edge は静止画しか出ない

### ISSUE THREAD

**Issue by dadaa** [dadaa/tpp-light#15]

**Comment by dadaa** [comment]
https://support.skyway.io/hc/ja/articles/115015688708
によればサポートできているはずなので、何か作法的な間違いがあるのかなぁ？

**Comment by dadaa** [comment]
手持ちの Windows 10 (Surface GO) では快適に動きました。背面カメラも。
なので、一度クローズします。

**Comment by yogurt0713** [comment]
開発者画面立ち上げてエラーをみてみましょうと思ったら，動きました！
