### ISSUE TITLE
android端末での操作問題

### ISSUE THREAD

**Issue by yogurt0713** [dadaa/tpp-light#16]
android端末の時はブラウザどうすれば？？

**Comment by dadaa** [comment]
いちおう、Chromeで動くのは確認しているんですけど、ページを切り替えても、カメラ接続が残っているような節があるので、そこだけ要確認です。

**Comment by dadaa** [comment]
Android Chrome はうまく動いている感じ

**Comment by dadaa** [comment]
ひとまずクローズしておきます
