### ISSUE TITLE
スタート画面の文言

### ISSUE THREAD

**Issue by yogurt0713** [dadaa/tpp-light#17]
connect to sample をconnect to TPP Lightに変更

**Comment by dadaa** [comment]
実はこの sample は room id で、URL のパラメータで送られます。
なので、ご存知の URL の sample のところを、TPP%20Light に置き換えると良いと思います！

**Comment by yogurt0713** [comment]
room idはユーザーが変えていいんですね！できました！

**Comment by dadaa** [comment]
よかった！
これクローズしておきますー

**Comment by yogurt0713** [comment]
そうでした．クローズ忘れてました！ありがとうございます！！

2020年5月3日(日) 13:14 dadaa <notifications@github.com>:
