### ISSUE TITLE
iPhone8 google chrome  not connected to app

### ISSUE THREAD

**Issue by yogurt0713** [dadaa/tpp-light#2]
iphone8 / google chromeでアプリでは実行ボタンを押しても動作しませんでした

**Comment by dadaa** [comment]
https://bugs.webkit.org/show_bug.cgi?id=208667

**Comment by dadaa** [comment]
動かないブラウザには、動かないことを示した方が良いかもしれませんね

**Comment by yogurt0713** [comment]
iphone -> chrome
windows 10 -> edge
ですかね

**Comment by dadaa** [comment]
https://bugs.webkit.org/show_bug.cgi?id=208667
によれば、iOS で webkit ベースのブラウザは safari 以外は動かないみたいですねー

**Comment by dadaa** [comment]
edge はエラーメッセージ見てみたいところ

**Comment by yogurt0713** [comment]
edge問題なく動いてました！
iOSでsafari以外は動かないならば，こちらはcloseしていいですね．

**Comment by dadaa** [comment]
スッキリしてきたｗ
